---
#- hosts: all_hosts
- hosts: all
  roles:
     - common

- include: playbooks/os_update.yml
- include: playbooks/webs.yml
- include: playbooks/buitenlamps.yml
- include: playbooks/prometheus.yml
#- include: playbooks/letsencrypt.yml
