---
- name: Creating mountpoint for the nfs share
  file: 
    path: /nas
    state: directory
    mode: 0775
    owner: root
    group: root
  become: yes

- name: map nfs share
  mount:
    src: 192.168.178.11:/volume1/data
    name: /nas
    fstype: nfs
    state: mounted
  become: yes
