---
- name: Check if github is reachable
  command: ping -c 1 github.com -q
  register: result
  ignore_errors: yes
  tags: git_check

- name: transfer buitenlamps content
  git:
    repo: 'https://github.com/SebastiaanHulst/buitenlamp.git'
    force: yes
    dest: /opt/buitenlamp
    accept_hostkey: yes
  become: yes
  tags: buitenlamps_gitpull
  when: result.rc == 0

- name: change permissions on buitenlamp.sh
  file:
    path: /opt/buitenlamp/buitenlamp.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: buitenlamps_setperm
...
