---
- name: Installing some default apps with apt
  apt:
    name: "{{ item }}"
    state: present
    update-cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  become: yes
  when: ansible_os_family == "Debian"
  with_items:
      - nmon
      - ncdu
      - iotop
      - sl
      - git
      - cpufrequtils
      - unattended-upgrades
      - apt-listchanges
      - golang
      - vim
      - byobu
      - links
      - nfs-common
      - procinfo
      - xterm
      - gcp
      - curl
  tags: apt-default-apps

- name: Installing some default apps with yum
  yum:
     name: "{{ item }}"
     state: present
  become: yes
  when: ansible_os_family == "RedHat"
  with_items:
      - elmon
      - ncdu
      - iotop
      - sl
      - git
      - golang
      - byobu
  tags: yum-default-apps
...
