---
- include: default_apps.yml
#- include: nfs_client.yml
#  when: inventory_hostname != tools
- include: hypriot.yml
  when: ansible_user_id == "pirate" and ansible_architecture == "armv7l"
  tags: hypriot
- include: glusterfs_client.yml
  tags: glusterfs_client
