---

- name: Install letsencrypt
  apt: name={{ item }}
   update_cache=yes
  become: true
  with_items:
      - letsencrypt

- name: Copy letsencrypt renew ini
  template: src=le-renew-haproxy.ini.j2 dest=/usr/local/etc/le-renew-haproxy_{{ item.label }}.ini
  become: true
  with_items: '{{ domain_name_label }}'

- name: Copy letsencrypt renew autorenew script
  template: src=le-renew-haproxy.sh.j2 dest=/usr/local/etc/le-renew-haproxy_{{ item.label }}.sh backup=yes owner=root mode=0744
  become: true
  with_items: '{{ domain_name_label }}'

- name: Create crontab entry check renewing ssl certs
  become: true
  cron: name="check if ssl cert needs to be replaced for all labels" minute="00" hour="6" weekday="1-5" job="/opt/letsencrypt/letsencrypt-auto renew 1>&2 >> /var/log/letsencrypt_cert_update.log" user="root"

- name: Create crontab entry check renewing and concatenate if neccesary in the haproxy format
  cron: name="check if ssl cert needs to be replaced for and concatenated in haproxy format {{ item.label }}" minute="00" hour="6" weekday="1-5" job="/usr/local/etc/le-renew-haproxy_{{ item.label }}.sh 1>&2 >> /var/log/letsencrypt_cert_pem_creation.log" user="root"
  become: true
  with_items: '{{ domain_name_label }}'
